// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoolBrackets_backend_dotnet.Data;

#nullable disable

namespace PoolBrackets_backend_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<decimal?>("EntryFee")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("entry_fee");

                    b.Property<string>("Format")
                        .HasColumnType("longtext")
                        .HasColumnName("format");

                    b.Property<int?>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("host_id");

                    b.Property<bool>("IsDisplayed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_displayed");

                    b.Property<bool>("IsHappen")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_happen");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("int")
                        .HasColumnName("number_of_players");

                    b.Property<string>("Slogan")
                        .HasColumnType("longtext")
                        .HasColumnName("slogan");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalPrize")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_prize");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_at");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("venue");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int?>("FirstPlayerId")
                        .HasColumnType("int")
                        .HasColumnName("first_player_id");

                    b.Property<int>("FirstPlayerPoint")
                        .HasColumnType("int")
                        .HasColumnName("first_player_point");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_finish");

                    b.Property<bool>("IsStart")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_start");

                    b.Property<int?>("NextMatchIdLose")
                        .HasColumnType("int")
                        .HasColumnName("next_match_id_lose");

                    b.Property<int?>("NextMatchIdWin")
                        .HasColumnType("int")
                        .HasColumnName("next_match_id_win");

                    b.Property<int>("NextMatchPosition")
                        .HasColumnType("int")
                        .HasColumnName("next_match_position");

                    b.Property<int>("RaceTo")
                        .HasColumnType("int")
                        .HasColumnName("race_to");

                    b.Property<string>("RoundName")
                        .HasColumnType("longtext")
                        .HasColumnName("round_name");

                    b.Property<int>("RoundType")
                        .HasColumnType("int")
                        .HasColumnName("round_type");

                    b.Property<int?>("SecondPlayerId")
                        .HasColumnType("int")
                        .HasColumnName("second_player_id");

                    b.Property<int>("SecondPlayerPoint")
                        .HasColumnType("int")
                        .HasColumnName("second_player_point");

                    b.Property<string>("TableNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("table_number");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("FirstPlayerId");

                    b.HasIndex("SecondPlayerId");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nation");

                    b.Property<int?>("Point")
                        .HasColumnType("int")
                        .HasColumnName("point");

                    b.Property<string>("Portrait")
                        .HasColumnType("longtext")
                        .HasColumnName("portrait");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.PlayerHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("match_date");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("match_id");

                    b.Property<int>("OpponentId")
                        .HasColumnType("int")
                        .HasColumnName("opponent_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("result");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_histories");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.PlayerInEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PlayerId", "EventId")
                        .IsUnique();

                    b.ToTable("player_in_events");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext")
                        .HasColumnName("nation");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.Event", b =>
                {
                    b.HasOne("PoolBrackets_backend_dotnet.Models.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.Match", b =>
                {
                    b.HasOne("PoolBrackets_backend_dotnet.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolBrackets_backend_dotnet.Models.Player", "FirstPlayer")
                        .WithMany()
                        .HasForeignKey("FirstPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolBrackets_backend_dotnet.Models.Player", "SecondPlayer")
                        .WithMany()
                        .HasForeignKey("SecondPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");

                    b.Navigation("FirstPlayer");

                    b.Navigation("SecondPlayer");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.Player", b =>
                {
                    b.HasOne("PoolBrackets_backend_dotnet.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.PlayerHistory", b =>
                {
                    b.HasOne("PoolBrackets_backend_dotnet.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolBrackets_backend_dotnet.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PoolBrackets_backend_dotnet.Models.PlayerInEvent", b =>
                {
                    b.HasOne("PoolBrackets_backend_dotnet.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolBrackets_backend_dotnet.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
